### ISSUE TITLE
Update all icons to more recent versions

### ISSUE THREAD

**Issue by Potherca** [plantuml-stdlib/Azure-PlantUML#29]
This issue is a catch-all for updating ALL the icons in this repo, rather than the individual MR/issues that are open(ed) now.

Individual issues will all be closed in favor of this issue, which takes the highest priority.

(It is assumed that all requests for missing icons will be resolved by using newer sources. If this turns out to be incorrect, those issues should be opened individually.)

## Overview of requested (missing) icons:

- [x] [Azure Firewall](https://github.com/phatcher/Azure-PlantUML/blame/feature/iconupdate/scripts/Config.yaml#L445-L448)  <details>
  ```
  - Source: Firewalls
    Target: AzureFirewall
  - Source: Azure Firewall Manager
    Target: AzureFirewallManager
  ```
    </details>

- [x] [Azure Blockchain Service](https://github.com/phatcher/Azure-PlantUML/blame/feature/iconupdate/scripts/Config.yaml#L65-L76)  <details>
  ```
  - Name: Blockchain
  Services:
  - Source: Azure Blockchain Service
    Target: AzurBlockchainService
  - Source: Azure Token Service
    Target: AzurBlockchainTokenService
  - Source: ABS Member
    Target: AzurBlockchainMember
  - Source: Consortium
    Target: AzureBlockchainConsortium
  - Source: Outbound Connection
    Target: AzureBlockchainConnection
  ```
    </details>

- [x] [Azure Subnet](https://github.com/phatcher/Azure-PlantUML/blame/feature/iconupdate/scripts/Config.yaml#L463-L464)  <details>
  ```
  - Source: VNet Subnets
    Target: AzureSubnet
  ```
    </details>

- [x] [Active Directory](https://github.com/phatcher/Azure-PlantUML/blame/feature/iconupdate/scripts/Config.yaml#L227-L250) <details>
  ```
  - Source: Azure Active Directory
    Target: AzureActiveDirectory
  - Source: Azure AD Domain Services
    Target: AzureActiveDirectoryDomainServices
  - Source: Azure AD B2C
    Target: AzureActiveDirectoryB2C
  - Source: Active Directory Connect Health
    Target: AzureActiveDirectoryConnectHealth
  - Source: Azure AD Identity Protection
    Target: AzureActiveDirectoryIdentityProtection
  - Source: Azure AD Roles and Administrators
    Target: AzureActiveDirectoryRolesAndAdministrators
  - Source: Groups
    Target: AzureActiveDirectoryGroup
  - Source: Users
    Target: AzureActiveDirectoryUser
  - Source: Identity Governance
    Target: AzureIdentityGovernance
  - Source: Managed Identities
    Target: AzureManagedIdentity
  - Source: Enterprise Applications
    Target: AzureEnterpriseApplication
  - Source: App Registrations
    Target: AzureAppRegistration
  ```
    </details>

- [ ] Azure App Configuration

- [ ] Azure Purview 

- [x] [Azure Synapse](https://github.com/phatcher/Azure-PlantUML/blame/feature/iconupdate/scripts/Config.yaml#L58-L59) <details>
  ```
  - Source: Azure Synapse Analytics
    Target: AzureSynapseAnalytics  
  ```
     </details>
  
- [ ] generic "Internet" cloud that looks "azure-ish"

- [x] [Device Provisioning Service](https://github.com/phatcher/Azure-PlantUML/blame/feature/iconupdate/scripts/Config.yaml#L305-L306) <details>
  ```
  - Source: Device Provisioning Services
    Target: AzureDeviceProvisioningService  
  ```
    </details>

- [x] [PowerBI](https://github.com/phatcher/Azure-PlantUML/blame/feature/iconupdate/scripts/Config.yaml#L172-L173) <details>
  ```
  - Source: Power BI Embedded
    Target: AzurePowerBIEmbedded  
  ```
    </details>
